### PR TITLE
adding info regarding browser native login prompt flag

### PR DESCRIPTION
**Pull request by paulbrodner**

### CODE REVIEW

**Comment by paulbrodner** [comment]
@andrei-rebegea  PR ready

**Comment by derekhulley** [comment]
No issues.  Please merge.

**Comment by killerboot** [comment]
@anxumalo Can this note be added in the current documentation? (This PR is quite old now).
From technical point it is a valid addition. But I'm not sure about adding more config options. The problem is that it is one of hundreds of others one can set for ACS. In my point of view we either need to have a pretty full list or just the minimum that we currently list.

**Comment by anxumalo** [comment]
@killerboot I've added this change in a new PR #55. May be we can close this PR?

**Comment by killerboot** [comment]
@anxumalo sure.
Closing this PR as it will addressed in #55.

**Pull request closed without merging**
