### PR TITLE
DEPLOY-655 added hostname option in ingress

### PR DESCRIPTION
**Pull request by mteodori**

### CODE REVIEW

**Comment by mteodori** [comment]
@killerboot change done, can you review, I will be doing on ent too

**Comment by killerboot** [comment]
The changes look good to me.
I just realised that the pull request is from your fork. Unfortunately we can't build from forks at the moment.
Can you please move your code to a branch of this project? So that we can check the build results for that change.
I will give you the write permissions on both deployment projects.

**Comment by mteodori** [comment]
thanks @killerboot pushed the branch here too
https://github.com/Alfresco/acs-community-deployment/tree/feature/DEPLOY-655
but cannot edit this PR to reference it as source, can you do it?

**Comment by killerboot** [comment]
@mteodori I can't. if this is not possible, please create a new one and reference this one there.
Sorry for inconvenience.

**Comment by mteodori** [comment]
been playing with the github API but there is no way to change the head branch, so created #51

**Pull request merged**
