### PR TITLE
Wait for middleware containers to wake up

### PR DESCRIPTION
**Pull request by otiai10**
# Problem

Sometimes `alfresco` container exits because of connection problems to the middleware containers.

# Solution

Let the `alfresco` container wait for others until they get waken up.

### CODE REVIEW

**Comment by killerboot** [comment]
Hi, thanks for your contribution.
The team is going to look at the proposal in this JIRA ticket:
https://issues.alfresco.com/jira/browse/REPO-4240

**Comment by otiai10** [comment]
@killerboot Thank you for comment.
Do you think I can update this pull-request reflecting to the concerns written in the JIRA ticket, or should wait for the review going on?

**Comment by killerboot** [comment]
@otiai10 It can work in both ways. We see that there is a problem and we definitely are planning to fix it.
As you can see in the JIRA there a few things that need to be changed before this can be merged in, so if you are happy to make the changes, go for it, we will be very grateful :)
If not, it is fine as well. I can't promise when this will be fixed as the ticket was not prioritised yet. Once the team will get it in the sprint this PR can act as a base for the further changes.

**Comment by otiai10** [comment]
@killerboot 
Is it possible to see Dockerfiles of these containers to see `CMD` or `ENTRYPOINT`? I checked Docker Hub but some of them don't have link to the files.

I'm writing code like following to make it sure that one container can wait for another.

```bash
#!/bin/bash

until `curl -sL http://alfresco:8080 >/dev/null`; do
    echo "Waiting for Alfresco waking up..."
    sleep 1s
done
echo "Detected Alfresco waken up"

# STAR UP SCRIPT SHOULD BE HERE
```

Reference: https://docs.docker.com/compose/startup-order/

Thank you

**Comment by killerboot** [comment]
@otiai10 You can find the Dockerfiles in various places:
* Alfresco: https://github.com/Alfresco/acs-community-packaging/blob/master/docker-alfresco/Dockerfile
* ActiveMQ: https://github.com/Alfresco/alfresco-docker-activemq/blob/master/Dockerfile
* Share: https://github.com/Alfresco/share/blob/master/packaging/docker/Dockerfile
* PostgreSQL is the official from here: https://hub.docker.com/_/postgres
* Solr6: https://github.com/Alfresco/SearchServices/blob/master/packaging/src/docker/Dockerfile

For Kubernetes we are using liveliness and readiness probes endpoints to do that:
https://github.com/Alfresco/acs-deployment/blob/996809aea28c81510c913742c4d2048923a98f51/helm/alfresco-content-services/templates/deployment-repository.yaml#L53
with the following URLs:
* /alfresco/api/-default-/public/alfresco/versions/1/probes/-ready-
* /alfresco/api/-default-/public/alfresco/versions/1/probes/-live-

We do not recommend using docker-compose in production, that's why we are not using those here.

**Comment by otiai10** [comment]
I saw some tricky and [project-specific](https://github.com/Alfresco/share/commit/29700d5be78a67fc5a7f7770f663add497d4195f) stuff which make it difficult to debug the development process for me: as a thrid-party developer.

I tried to [contribute other repos](https://github.com/Alfresco/share/pull/105) but finally found it's too long way to make the things done.

Now, I close this pull-request and leave it to you guys.
Thank you for your comments @killerboot , it was very learningful experience for me.

Best

**Comment by killerboot** [comment]
Thanks @otiai10. I'll pass this to Share team.

**Pull request closed without merging**
